<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <LangVersion>14</LangVersion>
  </PropertyGroup>

	<PropertyGroup>
		<OnixPluginUUID>d464baf6-f567-435c-bf7d-1a389a790743</OnixPluginUUID>
	</PropertyGroup> 

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Condition="'$(OS)' == 'Windows_NT'" Command="del &quot;$(OutDir)OnixRuntime.pdb&quot; &gt; NUL" IgnoreExitCode="true" />
        <Exec Condition="'$(OS)' == 'Windows_NT'" Command="del &quot;$(OutDir)OnixRuntime.dll&quot; &gt; NUL" IgnoreExitCode="true" />
        <Exec Condition="'$(OS)' != 'Windows_NT'" Command="rm &quot;$(OutDir)OnixRuntime.pdb&quot; &gt; NUL" IgnoreExitCode="true" />
        <Exec Condition="'$(OS)' != 'Windows_NT'" Command="rm &quot;$(OutDir)OnixRuntime.dll&quot; &gt; NUL" IgnoreExitCode="true" />
        <Exec Command="xcopy /C /Y &quot;$(SolutionDir)README.md&quot; &quot;$(ProjectDir)Assets&quot;" IgnoreExitCode="true" />
		<Exec Condition="'$(ServerPluginBuild)' != 'TRUE'" Command="rmdir /Q /S &quot;$(LOCALAPPDATA)\OnixClient\Client\Plugins\plugins\$(OnixPluginUUID)&quot;" IgnoreExitCode="true" />
		<Exec Condition="'$(ServerPluginBuild)' != 'TRUE'" Command="xcopy /S /C /I /Y &quot;$(OutDir)&quot; &quot;$(LOCALAPPDATA)\OnixClient\Client\Plugins\plugins\$(OnixPluginUUID)&quot;" />
		<Exec Condition="'$(ServerPluginBuild)' != 'TRUE'" Command="xcopy /E /C /I /Y &quot;$(ProjectDir)Assets&quot; &quot;$(LOCALAPPDATA)\OnixClient\Client\Plugins\plugins\$(OnixPluginUUID)\assets&quot;" />
		<Exec Condition="'$(ServerPluginBuild)' != 'TRUE'" Command="xcopy /C /Y &quot;$(ProjectDir)manifest.json&quot; &quot;$(LOCALAPPDATA)\OnixClient\Client\Plugins\plugins\$(OnixPluginUUID)&quot;" />
		<Exec Condition="'$(ServerPluginBuild)' != 'TRUE'" Command="echo OnixClient > &quot;$(LOCALAPPDATA)\OnixClient\Client\Plugins\plugins\$(OnixPluginUUID)\CompletePluginFlag.txt&quot;" />
		<Exec Condition="'$(ServerPluginBuild)' == 'TRUE'" Command="echo OnixClient > &quot;$(SolutionDir)BuildSuccessful.txt&quot;" />
	</Target>

    <ItemGroup>
        <Reference Condition="'$(ServerPluginBuild)' == 'TRUE'" Include="OnixRuntime"> </Reference>
        <Reference Condition="'$(ServerPluginBuild)' != 'TRUE'" Include="OnixRuntime">
        <HintPath>$(LOCALAPPDATA)\OnixClient\Client\Plugins\runtime\OnixRuntime.dll</HintPath>
        </Reference>

        <Analyzer Condition="'$(ServerPluginBuild)' == 'TRUE'" Include="$(ServerPluginBuildRuntime)/OnixRuntime.CodeGenerators.dll"/>
        <Analyzer Condition="'$(ServerPluginBuild)' != 'TRUE'" Include="$(LOCALAPPDATA)\OnixClient\Client\Plugins\runtime\OnixRuntime.CodeGenerators.dll"/>
    </ItemGroup>

    <PropertyGroup Condition="'$(ServerPluginBuild)' == 'TRUE'">
        <AssemblySearchPaths>$(ServerPluginBuildRuntime);$(AssemblySearchPaths);</AssemblySearchPaths>
    </PropertyGroup>

	<ItemGroup>
	  <Folder Include="Assets\" />
	</ItemGroup>

</Project>